name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: Test
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}, {\"swift_version\": \"5.10\"}]]"
      windows_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}]"
      enable_wasm_sdk_build: true
      wasm_sdk_build_command: swift build -Xcc -D_WASI_EMULATED_PTHREAD

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift Async Algorithms"
